name: Build Quartz Site
on:
  push:
    branches: ["test"]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: konstfish/quartz-build-action@v5
        with:
          # page title to be displayed in the browser
          page_title: "ZK-Wiki"
    #   - name: Upload artifact
    #     uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_site

